apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deploy
spec:
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: demoappk8.azurecr.io/demoapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-svc
spec:
  type: LoadBalancer
  selector:
    app: demoapp
  ports:
  - port: 80